---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: renovate-operator
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: "Renovate Dashboard"
    gethomepage.dev/group: "Kubernetes"
    gethomepage.dev/icon: "si-renovate.svg"
    gethomepage.dev/name: "Renovate"
    gethomepage.dev/app: "renovate"
spec:
  hostnames:
    - renovate.${SECRET_DOMAIN}
  parentRefs:
    - name: envoy-internal
      namespace: network
  rules:
    - backendRefs:
        - name: renovate-operator
          namespace: renovate
          port: 8081
---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: renovate-webhook
  annotations:
    gatus.home-operations.com/endpoint: |
      conditions:
        - "[STATUS] == 200"
spec:
  hostnames:
    - renovate-webhook.${SECRET_DOMAIN}
  parentRefs:
    - name: envoy-external
      namespace: network
  rules:
    - backendRefs:
        - name: renovate-operator-webhook
          namespace: renovate
          port: 8082
