---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: renovate-operator-secrets
  namespace: renovate
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: renovate-operator-secrets
  namespace: renovate
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: renovate-operator-secrets
subjects:
  - kind: ServiceAccount
    name: renovate-operator
    namespace: renovate
