---
apiVersion: v1
kind: Service
metadata:
  name: kasm-proxy-service
  namespace: external-ingresses
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 443
      name: http
---
apiVersion: v1
kind: Endpoints
metadata:
  name: kasm-proxy-service # Must be equal to Service name for automatic mapping
  namespace: external-ingresses
subsets:
  - addresses:
      - ip: 10.30.212.10 # IP address of your external service that you would like to proxy requests to
    ports:
      - port: 443
        name: http
        protocol: TCP

---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: kasm-passthrough
  namespace: external-ingresses
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: kasm-httproute

---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: kasm-httproute
  namespace: external-ingresses
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: kasm
    gethomepage.dev/group: Documents
    gethomepage.dev/name: kasm
    gethomepage.dev/href: "https://kasm.${SECRET_DOMAIN}/history"
spec:
  hostnames:
    - kasm.${SECRET_DOMAIN}
  parentRefs:
    - name: envoy-internal
      namespace: network
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: kasm-proxy-service
          namespace: external-ingresses
          port: 443
          weight: 1
