---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/gateway.envoyproxy.k8s.io/envoypatchpolicy_v1alpha1.json
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyPatchPolicy
metadata:
  name: envoy-internal-auth-cookie-patch
spec:
  jsonPatches:
    - type: type.googleapis.com/envoy.config.listener.v3.Listener
      name: network/envoy-internal-auth/https
      operation:
        op: add
        jsonPath: ..filters[*].typed_config.http_filters[?(@.name=="envoy.filters.http.oauth2")].typed_config
        value:
          # NOTE: these fields depend on the oauth2 filter implementation used
          # by Envoy Gateway. They are intended to instruct the oauth filter
          # to use the IdP session cookie and expected attributes.
          cookie_name: authentik_session
          cookie_domain: ".${SECRET_DOMAIN}"
          cookie_path: "/"
          cookie_samesite: None
          cookie_secure: true
    - type: type.googleapis.com/envoy.config.listener.v3.Listener
      name: network/envoy-internal-auth/https-quic
      operation:
        op: add
        jsonPath: ..filters[*].typed_config.http_filters[?(@.name=="envoy.filters.http.oauth2")].typed_config
        value:
          cookie_name: authentik_session
          cookie_domain: ".${SECRET_DOMAIN}"
          cookie_path: "/"
          cookie_samesite: None
          cookie_secure: true
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: envoy-internal-auth
  type: JSONPatch
