---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./authentik-oidc-secret.yaml
  - ./certificate.yaml
  - ./envoy.yaml
  - ./external.yaml
  - ./external-auth.yaml
  - ./internal.yaml
  - ./internal-auth.yaml
  - ./envoy-ext-auth-callback-httproute.yaml
  - ./podmonitor.yaml
