apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:meF5VWx7+7oau/Vy,iv:NG4xQZoS4bvEnnUzf5ec5gQwCrHoPXNQQDOCoEPN8lQ=,tag:fhPFo8kHliy5CCvALPgiPQ==,type:str]
sops:
  age:
    - recipient: age13jyzwq3g290ktqzmv6t0eytrww4zs76u3pg2e7cu7yeznjpk2fsqn4ngm2
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMWm15MnhsRWVvWk5kMEtj
        eDlKaDB0Z0tSNGxpdXZaU3NWTFM3TjFUOVVnClpiOG5OVU0vVUVXQXlQdHB4TTNu
        N2dKTTZwVzFjLzlGUnE4bk00K1lzaFUKLS0tIE56dktiYmpwa043a0NBR2Q3am5L
        MC9OU0NscVByMEd2c2VZOVBvWGxodjgKwVovOj9zeyzp6iqIHmNiEzvKn5WpqxYk
        NrtzKU8QovY9ZNNPEKbKQoCdY+08PZw5V6DEphD+M56P1Jq6IEjILw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-24T15:51:05Z"
  mac: ENC[AES256_GCM,data:3QPlHuL2QqcfhmUMo8uIcx3hfxZ2zHvvx4AfZE7or7gAzz3Pg9sMLNIFkGp1Ud2bwiUj/tyhl50hBAmK5eEvEH4t8RgX/aRHsGIyM37aeI+ynyXd5jviskKVuRaATQT/SDLq5JDPOttVi0p+5YdFYQU76n9dWHH0vV3SLNMAG3Y=,iv:3tnHFsEt5+BSVQIZCBJnZyWFXaObJ0NyeaTDXfVW4T4=,tag:JLen6P8y5LMCQy934VVmWw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
