---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: downloads
components:
  - ../../components/flux-alerts
  - ../../components/sops
resources:
  - ./namespace.yaml
  - ./autobrr/ks.yaml
  - ./bazarr/ks.yaml
  - ./cross-seed/ks.yaml
  - ./maintainerr/ks.yaml
  - ./mylar/ks.yaml
  - ./overseerr/ks.yaml
  - ./pinchflat/ks.yaml
  - ./prowlarr/ks.yaml
  - ./radarr/ks.yaml
  - ./readarr/ks.yaml
  - ./recyclarr/ks.yaml
  - ./sabnzbd/ks.yaml
  - ./sonarr/ks.yaml
  - ./tautulli/ks.yaml
