---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: database

components:
  - ../../components/flux-alerts
  - ../../components/sops

resources:
  - ./namespace.yaml
  # - ./cloudnative-pg/ks.yaml
  # - ./pgadmin/ks.yaml
  - ./dragonfly/ks.yaml
