---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./proxmox/ks.yaml
  - ./ha/ks.yaml
  - ./ha-music/ks.yaml
  - ./vpn/ks.yaml
  - ./dockge/ks.yaml
  - ./zigbee2mqtt1/ks.yaml
