---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname paperless
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  components:
    - ../../../../components/volsync
    - ../../../../components/keda/nas-nfs-scaler
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  interval: 1h
  path: ./kubernetes/apps/selfhosted/paperless/app
  prune: true
  postBuild:
    substitute:
      APP: *appname
      VOLSYNC_CLAIM: paperless-data
      VOLSYNC_CAPACITY: 15Gi
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: selfhosted
  timeout: 5m
  wait: false
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname paperless-ai
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  components:
    - ../../../../components/volsync
  interval: 10m
  path: ./kubernetes/apps/selfhosted/paperless/ai
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  postBuild:
    substitute:
      APP: *appname
      VOLSYNC_CLAIM: paperless-ai-data
      VOLSYNC_CAPACITY: 1Gi
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: selfhosted
  timeout: 5m
  wait: false
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname paperless-gpt
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  components:
    - ../../../../components/volsync
  interval: 10m
  path: ./kubernetes/apps/selfhosted/paperless/gpt
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  postBuild:
    substitute:
      APP: *appname
      VOLSYNC_CLAIM: paperless-gpt-data
      VOLSYNC_CAPACITY: 1Gi
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: selfhosted
  timeout: 5m
  wait: false
