---
apiVersion: v1
kind: Service
metadata:
  name: ocr-proxy-service
  namespace: external-ingresses
spec:
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000
      name: http
---
apiVersion: v1
kind: Endpoints
metadata:
  name: ocr-proxy-service # Must be equal to Service name for automatic mapping
  namespace: external-ingresses
subsets:
  - addresses:
      - ip: 10.30.3.10 # IP address of your external service that you would like to proxy requests to
    ports:
      - port: 8000
        name: http
        protocol: TCP

---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: ocr-passthrough
  namespace: external-ingresses
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: ocr-httproute

---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ocr-httproute
  namespace: external-ingresses
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: OCR
    gethomepage.dev/group: Documents
    gethomepage.dev/name: ocr
    gethomepage.dev/href: "https://ocr.${SECRET_DOMAIN}/history"
spec:
  hostnames:
    - ocr.${SECRET_DOMAIN}
  parentRefs:
    - name: envoy-internal
      namespace: network
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: ocr-proxy-service
          namespace: external-ingresses
          port: 8000
          weight: 1
