---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname proxmox
  namespace: flux-system
spec:
  targetNamespace: external-ingresses
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  path: ./kubernetes/apps/external-ingresses/proxmox/ingress
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 31m
  retryInterval: 1m
  timeout: 5m
