---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
data:
  docker.yaml: ""

  kubernetes.yaml: |
    mode: cluster
    gateway: true
    ingress: true
    traefik: false

  settings.yaml: |
    title: Homelab
    # background:
    #   image: https://raw.githubusercontent.com/joryirving/home-ops/main/.docs/assets/101518784_p0.jpg
    #   opacity: 20
    favicon: https://github.com/walkxcode/dashboard-icons/blob/main/png/heimdall.png
    theme: dark
    color: slate
    headerStyle: clean
    statusStyle: dot
    useEqualHeights: false
    fiveColumns: true
    quicklaunch:
      searchDescriptions: true
      hideInternetSearch: true
      showSearchSuggestions: true
      hideVisitURL: true
    layout:
      style: column
      G1:
        style: row
        header: false
        columns: 6
        Home Automation:
          style: column
          icon: home-assistant
        Apps:
          style: column
          icon: immich
        Development:
          style: column
          icon: code-server
        Kubernetes:
          style: column
          icon: kubernetes
        Documents:
          style: column
        Infrastructure:
          style: column
      G2:
        style: column
        header: false
        Media:
          style: column
          icon: jellyfin
        Downloads:
          style: row
          columns: 6
          icon: sonarr

  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: false
    - search:
        provider: duckduckgo
        focus: false
        target: _blank

  bookmarks.yaml: ""

  services.yaml: ""
