---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: headlamp
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: HeadLamp
    gethomepage.dev/group: Kubernetes
    gethomepage.dev/icon: si-commonworkflowlanguage.svg
    gethomepage.dev/name: Headlamp
    gethomepage.dev/app: headlamp
spec:
  hostnames:
    - headlamp.${SECRET_DOMAIN}
  parentRefs:
    - name: envoy-internal-auth
      namespace: network
  rules:
    - backendRefs:
        - name: headlamp
          namespace: observability
          port: 4466
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: headlamp-auth
  namespace: observability
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: headlamp
  oidc:
    provider:
      issuer: "https://sso.jaimenet.com/application/o/envoy-gateway/"
      authorizationEndpoint: "https://sso.jaimenet.com/application/o/authorize/"
      tokenEndpoint: "https://sso.jaimenet.com/application/o/token/"
    clientID: "XUzfQuGJXOB4vzKRCGzHc4d3EqR1MgXaLr8DfRRl"
    clientSecret:
      name: authentik-oidc-secret
      namespace: network
    redirectURL: "https://headlamp.jaimenet.com/oauth2/callback"
    logoutPath: "/oauth2/logout"
    scopes:
      - openid
      - profile
      - email
