---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: headlamp
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: HeadLamp
    gethomepage.dev/group: Kubernetes
    gethomepage.dev/icon: si-commonworkflowlanguage.svg
    gethomepage.dev/name: Headlamp
    gethomepage.dev/app: headlamp
spec:
  hostnames:
    - headlamp.${SECRET_DOMAIN}
  parentRefs:
    - name: envoy-internal-auth
      namespace: network
  rules:
    - backendRefs:
        - name: headlamp
          namespace: observability
          port: 4466
