---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: selfhosted
components:
  - ../../components/flux-alerts
  - ../../components/sops
resources:
  - ./namespace.yaml
  - ./paperless/ks.yaml
  - ./filebrowser/ks.yaml
  - ./it-tools/ks.yaml
  - ./homepage/ks.yaml
