---
apiVersion: v1
kind: Service
metadata:
  name: homeassistant-music-proxy-service
  namespace: external-ingresses
spec:
  ports:
    - port: 8095
      protocol: TCP
      targetPort: 8095
      name: http
---
apiVersion: v1
kind: Endpoints
metadata:
  name: homeassistant-music-proxy-service # Must be equal to Service name for automatic mapping
  namespace: external-ingresses
subsets:
  - addresses:
      - ip: 10.30.10.17 # IP address of your external service that you would like to proxy requests to
    ports:
    - name: http
      port: 8095
      protocol: TCP

---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: homeassistant-music-passthrough
  namespace: external-ingresses
spec:
  targetRef:
    group: gateway.networking.k8s.io  # Correct group
    kind: HTTPRoute  # Target the HTTPRoute, not the Service
    name: homeassistant-music-httproute
  # No healthCheck = assume always healthy
---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: homeassistant-music-httproute
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: Homeassistant-music
    gethomepage.dev/group: Home Automation
    gethomepage.dev/icon: si-homeassistant.svg
    gethomepage.dev/name: Homeassistant-music
    gethomepage.dev/showStats: "false"
spec:
  hostnames:
    - ha-music.${SECRET_DOMAIN}
  parentRefs:
    - name: envoy-internal
      namespace: network
  rules:
    - matches:
      - path:
          type: PathPrefix
          value: /
      backendRefs:
      - name: homeassistant-music-proxy-service
        port: 8095
        weight: 1
