---
# Ensure external/internal Gateway routes for Authentik point to the proxy
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: authentik-server
  namespace: selfhosted
  labels:
    app.kubernetes.io/managed-by: gitops-override
spec:
  hostnames:
    - sso.${SECRET_DOMAIN}
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: envoy-internal
      namespace: network
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: envoy-external
      namespace: network
      sectionName: https
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - group: ""
          kind: Service
          name: authentik-proxy
          namespace: selfhosted
          port: 80
          weight: 1
