---
web:
  port: $${CUSTOM_WEB_PORT}
metrics: true
debug: false

storage:
  type: sqlite
  caching: true
  path: ${GATUS_CONFIG_PATH}/gatus.db

ui:
  title: Status | Gatus
  header: Status
  logo: https://avatars.githubusercontent.com/u/7441527
  link: https://github.com/jaimemachado
  buttons:
    - name: Github
      link: https://github.com/jaimemachado
    - name: Homelab
      link: https://github.com/jaimemachadoneto/home-ops
# alerting:
#   pushover:
#     title: Gatus
#     application-token: $${PUSHOVER_TOKEN}
#     user-key: $${PUSHOVER_USER_KEY}
#     priority: 1
#     default-alert:
#       description: health-check failed
#       send-on-resolved: true
#       failure-threshold: 3
#       success-threshold: 3
connectivity:
  checker:
    target: 1.1.1.1:53
    interval: 1m

endpoints:
  - name: flux-webhook
    group: external
    url: https://flux-webhook.${SECRET_DOMAIN}
    interval: 1m
    client:
      dns-resolver: tcp://1.1.1.1:53
    conditions:
      - "[STATUS] == 404"
    alerts:
      - type: pushover
  # - name: heartbeat
  #   group: external
  #   ui:
  #     hide-hostname: true
  #     hide-url: true
  #   url: ${STATUS_PAGE_HEARTBEAT_URL}
  #   interval: 1m
  #   client:
  #     dns-resolver: tcp://1.1.1.1:53
  #   conditions:
  #     - "[STATUS] == 200"

  # - name: mainsail.chestr.dev
  #   group: certificates
  #   url: "tls://mainsail.chestr.dev:443"
  #   interval: 24h
  #   conditions:
  #     - "[CONNECTED] == true"
  #     - "[CERTIFICATE_EXPIRATION] > 336h"
  #   alerts:
  #     - type: pushover

  # - name: pikvm.chestr.dev
  #   group: certificates
  #   url: "tls://pikvm.chestr.dev:443"
  #   interval: 24h
  #   conditions:
  #     - "[CONNECTED] == true"
  #     - "[CERTIFICATE_EXPIRATION] > 336h"
  #   alerts:
  #     - type: pushover

  # - name: "*.chestr.dev"
  #   group: certificates
  #   url: "tls://external.chestr.dev:443"
  #   interval: 24h
  #   conditions:
  #     - "[CONNECTED] == true"
  #     - "[CERTIFICATE_EXPIRATION] > 336h"
  #   alerts:
  #     - type: pushover
