---
apiVersion: v1
kind: Service
metadata:
  name: vpn-proxy-service
  namespace: external-ingresses
spec:
  ports:
    - port: 51822
      protocol: UDP
      targetPort: 51822
      name: wireguard
---
apiVersion: v1
kind: Endpoints
metadata:
  name: vpn-proxy-service
  namespace: external-ingresses
subsets:
  - addresses:
      - ip: 10.30.10.15
    ports:
      - port: 51822
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vpn-proxy-ingress
  namespace: external-ingresses
  annotations:
    external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
    nginx.ingress.kubernetes.io/backend-protocol: "UDP"
    nginx.ingress.kubernetes.io/proxy-protocol: "true"
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
spec:
  ingressClassName: external-nginx
  rules:
    - host: vpn.${SECRET_DOMAIN}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vpn-proxy-service
                port:
                  number: 51822
---
apiVersion: v1
kind: Service
metadata:
  name: vpn-ui-proxy-service
  namespace: external-ingresses
spec:
  ports:
    - port: 10086
      protocol: TCP
      targetPort: 10086
      name: https
---
apiVersion: v1
kind: Endpoints
metadata:
  name: vpn-ui-proxy-service # Must be equal to Service name for automatic mapping
  namespace: external-ingresses
subsets:
- addresses:
  - ip: 10.30.10.16 # IP address of your external service that you would like to proxy requests to
  ports:
  - port: 10086
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vpn-ui-proxy-ingress
  namespace: external-ingresses
  annotations:
    external-dns.alpha.kubernetes.io/target: ingress-int.${SECRET_DOMAIN}
spec:
  ingressClassName: internal-nginx
  rules:
    - host: vpn-ui.${SECRET_DOMAIN}
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: vpn-ui-proxy-service
              port:
                number: 10086
