apiVersion: v1
kind: Service
metadata:
  name: vpn-ui-proxy-service
  namespace: external-ingresses
spec:
  ports:
    - port: 10086
      protocol: TCP
      targetPort: 10086
      name: https
---
apiVersion: v1
kind: Endpoints
metadata:
  name: vpn-ui-proxy-service # Must be equal to Service name for automatic mapping
  namespace: external-ingresses
subsets:
  - addresses:
      - ip: 10.30.10.16 # IP address of your external service that you would like to proxy requests to
    ports:
      - port: 10086
---
# Gateway for vpn-ui (internal)
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: vpn-ui-gateway
  namespace: external-ingresses
spec:
  gatewayClassName: internal-nginx
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: Same
        kinds:
          - kind: HTTPRoute

---
# HTTPRoute for vpn-ui
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: vpn-ui-route
  namespace: external-ingresses
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: Wireguard
    gethomepage.dev/group: Infrastructure
    gethomepage.dev/icon: si-wireguard.svg
    gethomepage.dev/name: Wireguard
    gethomepage.dev/app: wireguard
spec:
  parentRefs:
    - name: vpn-ui-gateway
  hostnames:
    - "vpn-ui.${SECRET_DOMAIN}"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: vpn-ui-proxy-service
          port: 10086
          weight: 1
