apiVersion: v1
kind: Service
metadata:
  name: vpn-ui-proxy-service
  namespace: external-ingresses
spec:
  ports:
    - port: 10086
      protocol: TCP
      targetPort: 10086
---
apiVersion: v1
kind: Endpoints
metadata:
  name: vpn-ui-proxy-service # Must be equal to Service name for automatic mapping
  namespace: external-ingresses
subsets:
- addresses:
  - ip: 10.30.10.16 # IP address of your external service that you would like to proxy requests to
  ports:
  - port: 10086
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vpn-ui-proxy-ingress
  namespace: external-ingresses
  annotations:
    external-dns.alpha.kubernetes.io/target: env-ingress-int.${SECRET_DOMAIN}
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Wireguard"
    gethomepage.dev/description: "Wireguard VPN UI"
    gethomepage.dev/group: "Infrastructure"
    gethomepage.dev/icon: "si-wireguard.svg"
    gethomepage.dev/href: "https://vpn-ui.${SECRET_DOMAIN}"
spec:
  ingressClassName: internal-nginx
  rules:
    - host: vpn-ui.${SECRET_DOMAIN}
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: vpn-ui-proxy-service
              port:
                number: 10086
