apiVersion: v1
kind: Service
metadata:
  name: vpn-ui-proxy-service
  namespace: external-ingresses
spec:
  ports:
    - port: 10086
      protocol: TCP
      targetPort: 10086
      name: http
---
apiVersion: v1
kind: Endpoints
metadata:
  name: vpn-ui-proxy-service # Must be equal to Service name for automatic mapping
  namespace: external-ingresses
subsets:
- addresses:
  - ip: 10.30.10.16 # IP address of your external service that you would like to proxy requests to
  ports:
  - port: 10086
    name: http
    protocol: TCP
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: vpn-ui-passthrough
  namespace: external-ingresses
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: vpn-ui-httproute

---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: vpn-ui-httproute
  namespace: external-ingresses
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Wireguard"
    gethomepage.dev/description: "Wireguard VPN UI"
    gethomepage.dev/group: "Infrastructure"
    gethomepage.dev/icon: "si-wireguard.svg"
    gethomepage.dev/href: "https://vpn-ui.${SECRET_DOMAIN}"
spec:
  hostnames:
    - vpn-ui.${SECRET_DOMAIN}
  parentRefs:
    - name: envoy-internal
      namespace: network
  rules:
    - matches:
      - path:
          type: PathPrefix
          value: /
      backendRefs:
        - name: vpn-ui-proxy-service
          namespace: external-ingresses
          port: 10086
          weight: 1
