---
apiVersion: v1
kind: Service
metadata:
  name: authentik-proxy
  namespace: selfhosted
  labels:
    app: authentik-proxy
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: authentik-proxy
  type: ClusterIP
