---
apiVersion: v1
kind: Service
metadata:
  name: zigbeetomqtt-garagem-proxy-service
  namespace: external-ingresses
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
      name: http
---
apiVersion: v1
kind: Endpoints
metadata:
  name: zigbeetomqtt-garagem-proxy-service # Must be equal to Service name for automatic mapping
  namespace: external-ingresses
subsets:
  - addresses:
      - ip: 10.30.10.18 # IP address of your external service that you would like to proxy requests to
    ports:
      - port: 8080
        name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zigbeetomqtt-garagem-proxy-ingress
  namespace: external-ingresses
  annotations:
    external-dns.alpha.kubernetes.io/target: "env-ingress-int.${SECRET_DOMAIN}"
    nginx.ingress.kubernetes.io/rewrite-target: /
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: Zigbee Garagem
    gethomepage.dev/group: Home Automation
    gethomepage.dev/icon: si-zigbee2mqtt.svg
    gethomepage.dev/name: Zigbee Garagem
    gethomepage.dev/app: zigbeegaragem
    gethomepage.dev/showStats: "false"
spec:
  ingressClassName: internal-nginx
  rules:
    - host: zigmqtt-garagem.${SECRET_DOMAIN}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: zigbeetomqtt-garagem-proxy-service
                port:
                  number: 80
