---
apiVersion: v1
kind: Service
metadata:
  name: dockge-proxy-service
  namespace: external-ingresses
spec:
  ports:
    - port: 5001
      protocol: TCP
      targetPort: 5001
      name: https
---
apiVersion: v1
kind: Endpoints
metadata:
  name: dockge-proxy-service # Must be equal to Service name for automatic mapping
  namespace: external-ingresses
subsets:
  - addresses:
      - ip: 10.30.3.10 # IP address of your external service that you would like to proxy requests to
    ports:
      - port: 5001
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dockge-proxy-ingress
  namespace: external-ingresses
spec: {}
---
# Gateway for dockge (replaces Ingress)
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: dockge-gateway
  namespace: external-ingresses
spec:
  gatewayClassName: internal-nginx
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: Same
        kinds:
          - kind: HTTPRoute

---
# HTTPRoute for dockge
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: dockge-route
  namespace: external-ingresses
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: Dockge
    gethomepage.dev/group: Infrastructure
    gethomepage.dev/icon: si-docker.svg
    gethomepage.dev/name: Dockge
    gethomepage.dev/app: dockge
spec:
  parentRefs:
    - name: dockge-gateway
  hostnames:
    - "dockge.${SECRET_DOMAIN}"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: dockge-proxy-service
          port: 5001
          weight: 1
  # tls:
  # - hosts:
  #     - dockge.${SECRET_DOMAIN}
  #   secretName: "${SECRET_DOMAIN/./-}-production-tls"
