---
apiVersion: v1
kind: Service
metadata:
  name: dockge-proxy-service
  namespace: external-ingresses
spec:
  ports:
    - port: 5001
      protocol: TCP
      targetPort: 5001
---
apiVersion: v1
kind: Endpoints
metadata:
  name: dockge-proxy-service # Must be equal to Service name for automatic mapping
  namespace: external-ingresses
subsets:
- addresses:
  - ip: 10.30.3.10 # IP address of your external service that you would like to proxy requests to
  ports:
  - port: 5001
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dockge-proxy-ingress
  namespace: external-ingresses
  annotations:
    external-dns.alpha.kubernetes.io/target: env-ingress-int.${SECRET_DOMAIN}
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: Docker
    gethomepage.dev/group: Infrastructure
    gethomepage.dev/icon: si-docker.svg
    gethomepage.dev/name: Docker
    gethomepage.dev/app: docker
spec:
  ingressClassName: internal-nginx
  rules:
    - host: dockge.${SECRET_DOMAIN}
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: dockge-proxy-service
              port:
                number: 5001
  # tls:
  # - hosts:
  #     - dockge.${SECRET_DOMAIN}
  #   secretName: "${SECRET_DOMAIN/./-}-production-tls"
