---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: readarr-db
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: readarr-db-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        INIT_POSTGRES_DBNAME: readarr_main readarr_log
        INIT_POSTGRES_HOST: postgres16-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        READARR__POSTGRES__HOST: postgres16-rw.database.svc.cluster.local
        READARR__POSTGRES__PORT: "5432"
        READARR__POSTGRES__USER: "{{ .POSTGRES_USER }}"
        READARR__POSTGRES__PASSWORD: "{{ .POSTGRES_PASS }}"
        READARR__POSTGRES__MAINDB: readarr_main
        READARR__POSTGRES__LOGDB: readarr_log
  dataFrom:
    - extract:
        key: readarr
