apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rclone
  namespace: selfhosted
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: rclone-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        RCLONE_USERNAME: "{{ .rclone_admin_username }}"
        RCLONE_PASSWORD: "{{ .rclone_admin_password }}"
        # Keep as-is if 1Password already stores it with real newlines
        RCLONE_CONF: |
          {{ .rclone_conf }}
  dataFrom:
    - extract:
        key: rclone
      rewrite:
        - regexp:
            source: "(.*)"
            target: "rclone_$1"
